---
- hosts: cit
  become: yes
  remote_user: devops
  tasks:
    - name: install httpd
      apt: 
        name: httpd
        state: present 
    - name: restart httpd service
      service:
        name: httpd
        state: started
        enabled: yes 
